# galaxy for hutlab

FROM bgruening/galaxy-stable

MAINTAINER biobakery, hutlab@googlegroups.com


ENV GALAXY_CONFIG_BRAND Hutlab

WORKDIR /galaxy-central

COPY ./job_conf.xml /galaxy-central/config/job_conf.xml
COPY ./install_galaxy_python_deps.sh /galaxy-central/install_galaxy_python_deps.sh
COPY ./install.R /galaxy-central/install.R
COPY ./dependency_resolvers_conf.xml /galaxy-central/config/dependency_resolvers_conf.xml
COPY ./integrated_tool_panel.xml.lefse_fixed_order /galaxy-central/integrated_tool_panel.xml.lefse_fixed_order
COPY ./welcome.html $GALAXY_CONFIG_DIR/web/welcome.html
COPY ./datatypes_conf.xml /galaxy-central/config/datatypes_conf.xml
COPY ./tool_conf.xml /galaxy-central/config/tool_conf.xml
COPY ./install_tools.sh /usr/local/bin/install_tools.sh
COPY ./run_cron.sh /usr/local/bin/run_cron.sh
COPY ./run_db_backups.sh /usr/local/bin/run_db_backups.sh
COPY ./crontab /etc/cron.d/galaxy


# RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9 && \
# RUN    sh -c "echo deb http://archive.linux.duke.edu/cran/bin/linux/ubuntu trusty/ > /etc/apt/sources.list.d/r_cran.list" && \
RUN    apt-get update -qq 
RUN    apt-get upgrade -y 
# RUN    apt-get install --no-install-recommends -y python-software-properties software-properties-common 
# RUN    libfreetype6-dev bowtie bowtie2 libhdf5-dev texlive-binaries
# RUN    r-base-core r-base-dev r-cran-mvtnorm r-cran-multcomp r-cran-sandwich r-cran-th.data r-cran-zoo r-cran-testthat 
# RUN    r-cran-vegan r-cran-gam r-cran-gbm r-cran-pscl r-cran-robustbase 
# RUN    ssh libopenmpi-dev openmpi-bin 
RUN    sudo -H -u galaxy /galaxy-central/install_galaxy_python_deps.sh 
RUN    chmod +x /usr/bin/startup 
RUN    chmod +x /usr/local/bin/install_tools.sh 
RUN    chmod g-w /var/log 
RUN    ln -s /galaxy-central /usr/local/galaxy-dist 
# RUN    R CMD BATCH -q /galaxy-central/install.R /galaxy-central/r_deps_installed.log && \
RUN    chmod +x /usr/bin/startup /usr/local/bin/install_* 
RUN    chmod g-w /var/log 
RUN    ln -s /galaxy-central /usr/local/galaxy-dist 
RUN    touch galaxy_install.log && chown galaxy:galaxy galaxy_install.log 
RUN    add-tool-shed --u 'http://testtoolshed.g2.bx.psu.edu/' --name 'Test Tool Shed' && sleep 5 
# RUN    install-repository "-u https://testtoolshed.g2.bx.psu.edu/ -o george-weingart --name lefse --panel-section-name LEfSe -r a6284ef17bf3" && sleep 5 
# RUN    install-repository "-u https://testtoolshed.g2.bx.psu.edu/ -o george-weingart --name metaphlan --panel-section-name MetaPhlAn -r d31b701b44ee" && sleep 5 
# RUN    install-repository "-u https://testtoolshed.g2.bx.psu.edu/ -o george-weingart --name micropita --panel-section-name microPITA -r 61e311c4d2d0" && sleep 5 
# RUN    install-repository "-u https://testtoolshed.g2.bx.psu.edu/ -o george-weingart --name maaslin --panel-section-name MaAsLin -r 4450aa4ecc84" 
# RUN    bash /usr/local/bin/install_tools.sh 
# RUN    chown -Rf galaxy:galaxy /galaxy-central/ 
# RUN    apt-get update \
#        && apt-get remove -y nginx-common nginx-extras \
#        && apt-get install -y nginx-common=1.4.6-1ubuntu3.4ppa1 nginx-extras=1.4.6-1ubuntu3.4ppa1\
#        && apt-get autoremove -y \
#        && apt-get clean \
#        && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install Visualisation
# RUN install-biojs msa

# Adding the tool definitions to the container
# ADD tools.yaml $GALAXY_ROOT/tools.yaml

# Install deepTools
# RUN install-tools $GALAXY_ROOT/tools.yaml

# Mark folders as imported from the host.
VOLUME ["/export/", "/data/", "/var/lib/docker"]

# Expose port 80 (webserver), 21 (FTP server), 8800 (Proxy)
EXPOSE :80
EXPOSE :21
EXPOSE :8800

# Autostart script that is invoked during container start
CMD ["/usr/bin/startup"]